CREATE TABLE DEPLOY_TARGET
(
	 SEQ					INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,
	 SYSTEM_NAME            VARCHAR2(50) NOT NULL,
	 SUB_SYSTEM				VARCHAR2(50) NOT NULL,
     NODE_NO		   		INTEGER NOT NULL,
     IP_ADDR				VARCHAR2(50) NOT NULL,
     LISTEN_PORT			INTEGER		 NOT NULL,
     USE_YN					VARCHAR2(2),
     CONSTRAINT UN_DEPLOY_TARGET unique (SYSTEM_NAME, SUB_SYSTEM, NODE_NO)
)

CREATE TABLE DEPLOY_COMMAND
(
	 CMD_SEQ INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT , 
     SYSTEM_NAME  VARCHAR2(50) NOT NULL,
     SUB_SYSTEM	  VARCHAR2(50) NOT NULL,
	 NODE_NO  INTEGER NOT NULL,
     COMMAND  VARCHAR2(50) NOT NULL,
	 SHELL_COMMAND  VARCHAR2(50),
	 SHELL_NAME  VARCHAR2(50),
	 SHELL_PARAMS  VARCHAR2(50),
     USE_YN  VARCHAR2(2),
     CONSTRAINT UN_DEPLOY_COMMAND unique (SYSTEM_NAME, SUB_SYSTEM, NODE_NO)
)


INSERT INTO DEPLOY_TARGET VALUES(null, 'PORTAL', 'APP', 1, '10.255.68.106', 9090, 'Y');
INSERT INTO DEPLOY_TARGET VALUES(null, 'PORTAL', 'OZ', 1, '10.255.68.106', 9090, 'Y');
INSERT INTO DEPLOY_TARGET VALUES(null, 'PORTAL', 'BIZACTOR', 1, '10.255.68.106', 9090, 'Y');

INSERT INTO DEPLOY_TARGET VALUES(null, 'PORTAL', 'APP', 2, '10.255.68.106', 9090, 'Y');
INSERT INTO DEPLOY_TARGET VALUES(null, 'PORTAL', 'OZ', 2, '10.255.66.172', 9090, 'Y');
INSERT INTO DEPLOY_TARGET VALUES(null, 'PORTAL', 'BIZACTOR', 2, '10.255.66.172', 9090, 'Y');

INSERT INTO DEPLOY_COMMAND VALUES(null, 'PORTAL', 'APP', 1,  '/home/tomcat/deploy/portalrun.sh', '', '', '', 'Y');
INSERT INTO DEPLOY_COMMAND VALUES(null, 'PORTAL', 'OZ', 1,  '/home/tomcat/deploy/ozrun.sh', '', '', '', 'Y');
INSERT INTO DEPLOY_COMMAND VALUES(null, 'PORTAL', 'BIZACTOR', 1,  '/home/tomcat/deploy/barun.sh', '', '', '', 'Y');

INSERT INTO DEPLOY_COMMAND VALUES(null, 'PORTAL', 'APP', 2,  '/home/tomcat/deploy/portalrun.sh', '', '', '', 'Y');
INSERT INTO DEPLOY_COMMAND VALUES(null, 'PORTAL', 'OZ', 2,  '/home/tomcat/deploy/ozrun.sh', '', '', '', 'Y');
INSERT INTO DEPLOY_COMMAND VALUES(null, 'PORTAL', 'BIZACTOR', 2,  '/home/tomcat/deploy/barun.sh', '', '', '', 'Y');
